### ISSUE TITLE
ImportError: No module named matplotlib.pyplot

### ISSUE THREAD

**Issue by lilymag** [innisfree/LHCO_reader#1]
Hi,
I am very interested in your LHCO_reader. However,  When I run it, a error is reported.

```
$ python
Python 2.7.3 (default, Apr 20 2012, 22:44:07) 

[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from LHCO_reader import LHCO_reader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "LHCO_reader/LHCO_reader.py", line 84, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
```

In addition, could you share a completed code which is used to analyze a specific signal or background.
It will be very helpful for me to understand and use your great LHCO_reader.

Many thanks

**Comment by lilymag** [comment]
Hi,

I solve the problem using 

```
sudo apt-get install python-matplotlib.
```
