### ISSUE TITLE
Error when printing events: TypeError: __init__() got an unexpected keyword argument 'header'

### ISSUE THREAD

**Issue by andrewfowlie** [innisfree/LHCO_reader#2]
Hello,

`print events[0]` works well, but `print events` does not work:

```
    Python 2.7.3 (default, Apr 20 2012, 22:44:07) 
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import LHCO_reader
    >>> events = LHCO_reader.Events(f_name="example.lhco")
    >>> print events[0]
    +----------+--------+-------+--------+-------+------+------+-------+
    |  Object  |  eta   |  phi  |   PT   | jmass | ntrk | btag | hadem |
    +----------+--------+-------+--------+-------+------+------+-------+
    | electron | -0.745 | 4.253 | 286.72 |  0.0  | -1.0 | 0.0  |  0.0  |
    | electron | -0.073 | 4.681 | 44.56  |  0.0  | 1.0  | 0.0  |  0.0  |
    |   jet    | -0.565 | 1.126 | 157.44 | 12.54 | 16.0 | 0.0  |  0.57 |
    |   jet    | -0.19  | 1.328 | 130.96 |  12.3 | 18.0 | 0.0  | 10.67 |
    |   jet    | 0.811  | 6.028 | 17.49  |  3.47 | 8.0  | 0.0  |  2.37 |
    |   jet    | 0.596  | 0.853 | 12.47  |  2.53 | 7.0  | 0.0  |  1.26 |
    |   jet    | -1.816 | 0.032 |  6.11  |  1.18 | 0.0  | 0.0  |  0.56 |
    |   jet    | 0.508  | 1.421 |  6.01  |  0.94 | 7.0  | 0.0  |  2.59 |
    |   MET    |  0.0   | 2.695 | 21.43  |  0.0  | 0.0  | 0.0  |  0.0  |
    +----------+--------+-------+--------+-------+------+------+-------+
    >>> print events
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "LHCO_reader.py", line 463, in __str__
        table = pt(header=False)
    TypeError: __init__() got an unexpected keyword argument 'header'
```

**Comment by andrewfowlie** [comment]
Dear @lilymag,

I think the problem is with prettytable (not LHCO_reader)  - it doesn't seem to recognize the keyword "header".  I see you're running python2.7.3 - a little bit old, but I'd be surprised if prettytable wasn't python2.7.x compatible. 

### Try to reproduce the bug with this minimal example

```
from prettytable import PrettyTable as pt
x = pt(header=False)
```

### Check your version of prettytable

```
python -c "import prettytable as pt; print pt.__version__"
```

or if you use pip:

```
  pip list | grep prettytable
```

### Update prettytable

If you use pip,

```
pip install prettytable --upgrade
pip list | grep prettytable
```

If you don't have pip and can't install it, see [the wiki](https://code.google.com/p/prettytable/wiki/Installation).

Check whether updating prettytable fixes the bug.

**Comment by lilymag** [comment]
Hi,
The problem is from the low version of prettytable 0.5.

Using the command:

```
sudo easy_install -U prettytable
```

prettytable is updated to 0.7.2, then the the problem is well solved.

Best
Lily
